#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and bad luck from China for the 4th loop iteration, bad luck from Japan for the 9th loop iteration and bad luck from Italy for the 17th loop iteration
i=1
while [ $i -le 20 ]
do
	echo $i
	(( i++ ))
	case $i in
	5) echo "bad luck from China";;
	10) echo "bad luck from Japan";;
	18) echo "bad luck from Italy";;
	esac
done
